version: '3'
services: 
    app:
        image: ghcr.io/elektryx/firefly-iii-fints-importer:latest
        volumes:
            - ./data/configurations:/app/configurations
        ports: 
            - 8080:8080
